<div class="forms-container">
<div class="form-1">
	<header>
		<h1>Número de Identificação Social</h1>
		<p>Preencha o formulário para se cadastrar e receber um número NIS.</p>
	</header>

	<form id="nis-form-1">
		<fieldset>
			<div class="fieldset-wrapper">
				<div class="full-name">
					<div class="input-wrapper">
						<label for="name">Nome</label>
						<input name="full-name" type="text" id="name" placeholder="Digite seu nome completo">
					</div>
		</fieldset>
		<button type="submit" class="save-button">
			Gerar NIS
		</button>
	</form>
</div>

<br>
<br>

<div class="form-2">
	<header>
		<h1>Consulta de Número de Identificação Social</h1>
		<p>Insira seu número de cadastro para verificar seu nome associado.</p>
	</header>

	<form id="nis-form-2">
		<fieldset>
			<div class="fieldset-wrapper">
				<div class="full-name">
					<div class="input-wrapper">
						<label for="number">NIS</label>
						<input name="nis-number" type="number" id="number" placeholder="Digite seu NIS (11 digitos)">
					</div>
		</fieldset>
		<button type="submit" class="save-button">
			Consultar
		</button>
	</form>	
</div>
</div>